document.querySelector('.menu').addEventListener('click', e => { const open = document.querySelector('nav').classList.toggle('open'); e.currentTarget.setAttribute('aria-expanded', String(open)); });
document.querySelectorAll('nav a').forEach(a => a.addEventListener('click', () => { document.querySelector('nav').classList.remove('open'); document.querySelector('.menu').setAttribute('aria-expanded','false'); }));
const data=window.NUGI;
const heading=(number,title,aside='')=>`<div class="section-head"><div>${['01','03','04','06'].includes(number) ? '' : `<p class="eyebrow">${number} / NUGI</p>`}<h2>${title}</h2></div>${aside?`<p>${aside}</p>`:''}</div>`;
const steps=[['Understand the Story','Every project starts with understanding the content, audience, and purpose behind the video.'],['Craft with Precision','From pacing and cuts to subtitles, B-roll, sound design, and visual elements, every detail has a purpose.'],['Deliver with Impact','The final edit is polished and optimized for its platform, ready to capture attention and communicate the message effectively.']];
document.querySelector('#sections').innerHTML=`
<section class="wrap" id="about"><div class="about-grid"><div>${heading('01','THE EDITOR<br>BEHIND THE CUT.')}<span class="outline-word">ABOUT ME</span></div><div class="about-copy"><p>I’m Nugi, a video editor focused on transforming raw footage into engaging content for creators and brands.</p><p>I’ve been editing since 2020, working across short-form, long-form, podcast, and digital content.</p></div></div><div class="stats">${[['5+','Years Editing'],['100+','Videos Edited'],['3+','Years Working With Creators'],['3+','Main Content Niches','Crypto, Ai, Gym']].map(([n,t,s])=>`<div><strong>${n}</strong><p>${t}</p>${s?`<small>${s}</small>`:''}</div>`).join('')}</div></section>
<section class="wrap" id="work">${heading('03','FEATURED WORK','Short stories. Long conversations. Lasting impressions.')}<div class="filters" role="group" aria-label="Filter projects">${['SHORT CONTENT','LONG CONTENT','PODCAST CONTENT'].map((x,i)=>`<button aria-pressed="${i===0}" data-category="${x}">${x}</button>`).join('')}</div><div class="projects"></div></section>
<section class="process-surface" id="process"><div class="wrap">${heading('04','FLOW EDITING PROCESS')}<div class="three-grid">${steps.map(([t,p],i)=>`<article class="process-card"><span class="step">0${i+1}</span><div class="step-line"></div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></div></section>
<section class="wrap testimonials" id="testimonials">${heading('06','CLIENT TESTIMONIALS')}<div class="three-grid">${data.testimonials.map(t=>`<article><span class="quote" aria-hidden="true">“</span><blockquote>${t.text}</blockquote><div class="person"><span class="avatar">${t.initials}</span><strong>${t.name}</strong></div></article>`).join('')}</div></section>
<section class="cta wrap"><h2>HAVE A PROJECT<br><span class="red">IN MIND?</span></h2><p>Let’s turn your footage<br>into something worth watching.</p><a class="button primary" href="https://wa.me/6289676802994" target="_blank" rel="noopener noreferrer">LET’S WORK TOGETHER ↗</a></section>
<footer class="wrap"><div><a class="brand" href="#home">NUGI<span>®</span></a></div><p>Based in Surabaya, Indonesia</p><div class="socials"><a id="instagram-link" href="#home" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div></footer>
<dialog aria-labelledby="video-title"><div class="dialog-head"><h3 id="video-title">Project preview</h3><button class="close" aria-label="Close video">✕</button></div><video controls playsinline preload="none"></video><p class="asset-note">Sample footage only. Nugi’s final video will replace this clip.</p></dialog>`;
const modal=document.querySelector('dialog'),fullVideo=modal.querySelector('video');
function openVideo(title,url){document.querySelector('#video-title').textContent=title;fullVideo.src=url;modal.showModal();fullVideo.play().catch(()=>{});}
function closeVideo(){fullVideo.pause();fullVideo.removeAttribute('src');fullVideo.load();modal.close();}

modal.querySelector('.close').onclick=closeVideo;modal.addEventListener('cancel',e=>{e.preventDefault();closeVideo()});modal.addEventListener('click',e=>{if(e.target===modal)closeVideo()});
let stops=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function renderProjects(category){stops.forEach(fn=>fn());stops=[];const list=data.projects.filter(p=>p.category===category);document.querySelector('.projects').innerHTML=list.map(p=>`<article class="project ${p.category!=='SHORT CONTENT'?'project--wide':''}"><div class="project-media" role="button" tabindex="0" aria-label="Play ${p.name} with sound"><video muted autoplay loop playsinline preload="metadata" src="${p.video}" aria-label="${p.name} video"></video></div><div class="project-meta"><div><h3>${p.name}</h3><p>${p.client}</p></div><span>↗</span></div></article>`).join('');document.querySelectorAll('.project').forEach(card=>{const media=card.querySelector('.project-media'),v=card.querySelector('video');async function toggleAudio(){v.muted=!v.muted;media.classList.toggle('audio-on',!v.muted);media.setAttribute('aria-label',v.muted?'Play with sound':'Mute video');try{await v.play()}catch{}}media.addEventListener('click',toggleAudio);media.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleAudio()}});const io=new IntersectionObserver(entries=>{if(entries[0].isIntersecting)v.play().catch(()=>{});else v.pause()});io.observe(card);stops.push(()=>io.disconnect())});}
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderProjects(b.dataset.category)});renderProjects('SHORT CONTENT');
document.addEventListener('visibilitychange',()=>{if(document.hidden){document.querySelectorAll('video').forEach(v=>v.pause())}});
if(data.instagram)document.querySelector('#instagram-link').href=data.instagram;
if(data.email)document.querySelector('#email-link').href='mailto:'+data.email;

const socialIcons={instagram:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"></rect><circle cx="12" cy="12" r="4"></circle><circle class="ig-dot" cx="17.4" cy="6.7" r="1"></circle></svg>',tiktok:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4c.6 2.1 2 3.6 4 4v3.1c-1.5 0-2.9-.5-4-1.4v5.7a5.4 5.4 0 1 1-4.6-5.3v3.1a2.4 2.4 0 1 0 1.6 2.2V4h3z"></path></svg>',youtube:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 12c0 3.5-.4 5.7-1 6.5-.6.7-2.7 1-8 1s-7.4-.3-8-1C3.4 17.7 3 15.5 3 12s.4-5.7 1-6.5c.6-.7 2.7-1 8-1s7.4.3 8 1c.6.8 1 3 1 6.5z"></path><path class="play-triangle" d="m10 8 5 4-5 4z"></path></svg>'};
document.querySelector('#client-cards').innerHTML=data.clients.map(c=>`<article class="client-card"><div class="client-icon"><img src="${c.icon}" alt="${c.name}"></div><div class="client-copy"><h3>${c.name}</h3><p>${c.description}</p></div><div class="client-socials">${['instagram','tiktok','youtube'].filter(network=>c[network]).map(network=>`<a class="client-social" href="${c[network]}" target="_blank" rel="noopener noreferrer" aria-label="Visit ${c.name} on ${network}">${socialIcons[network]}</a>`).join('')}</div></article>`).join('');
